/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0502e84f648e011e96fefd0a2f561420)
interface __BaseEnv_Env {
  PO_TOKEN_KV: KVNamespace;
  BROWSER: BrowserRun;
  TOKEN_RATE_LIMITER: DurableObjectNamespace<import('./src/index').TokenRateLimiter>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
    durableNamespaces: 'TokenRateLimiter';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
