/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8db8f41ade0d026a419b860075f7bcbd)
declare namespace Cloudflare {
  interface Env {
    PO_TOKEN_KV: KVNamespace;
    TOKEN_MINT_RATE_LIMITER: RateLimit;
    BROWSER: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
